// Generated by gencpp from file common_interfaces_test_msgs/Container.msg
// DO NOT EDIT!


#ifndef COMMON_INTERFACES_TEST_MSGS_MESSAGE_CONTAINER_H
#define COMMON_INTERFACES_TEST_MSGS_MESSAGE_CONTAINER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include "SubContainer.h"

namespace common_interfaces_test_msgs
{
template <class ContainerAllocator>
struct Container_
{
  typedef Container_<ContainerAllocator> Type;

  Container_()
    : cont1()
    , cont1_valid(false)
    , cont2()
    , cont3()
    , cont3_valid(false)
    , cont4()
    , field1(0)
    , field1_valid(false)
    , field2(0)  {
    }
  Container_(const ContainerAllocator& _alloc)
    : cont1(_alloc)
    , cont1_valid(false)
    , cont2(_alloc)
    , cont3(_alloc)
    , cont3_valid(false)
    , cont4(_alloc)
    , field1(0)
    , field1_valid(false)
    , field2(0)  {
  (void)_alloc;
    }



   typedef  ::common_interfaces_test_msgs::SubContainer_<ContainerAllocator>  _cont1_type;
  _cont1_type cont1;

   typedef uint8_t _cont1_valid_type;
  _cont1_valid_type cont1_valid;

   typedef  ::common_interfaces_test_msgs::SubContainer_<ContainerAllocator>  _cont2_type;
  _cont2_type cont2;

   typedef  ::common_interfaces_test_msgs::SubContainer_<ContainerAllocator>  _cont3_type;
  _cont3_type cont3;

   typedef uint8_t _cont3_valid_type;
  _cont3_valid_type cont3_valid;

   typedef  ::common_interfaces_test_msgs::SubContainer_<ContainerAllocator>  _cont4_type;
  _cont4_type cont4;

   typedef uint32_t _field1_type;
  _field1_type field1;

   typedef uint8_t _field1_valid_type;
  _field1_valid_type field1_valid;

   typedef uint32_t _field2_type;
  _field2_type field2;




  typedef boost::shared_ptr< ::common_interfaces_test_msgs::Container_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_interfaces_test_msgs::Container_<ContainerAllocator> const> ConstPtr;

}; // struct Container_

typedef ::common_interfaces_test_msgs::Container_<std::allocator<void> > Container;

typedef boost::shared_ptr< ::common_interfaces_test_msgs::Container > ContainerPtr;
typedef boost::shared_ptr< ::common_interfaces_test_msgs::Container const> ContainerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_interfaces_test_msgs::Container_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_interfaces_test_msgs::Container_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace common_interfaces_test_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'common_interfaces_test_msgs': ['/home/dseredyn/ws_sim_safety2/sim/src/common_interfaces_test_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::common_interfaces_test_msgs::Container_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_interfaces_test_msgs::Container_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_interfaces_test_msgs::Container_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_interfaces_test_msgs::Container_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_interfaces_test_msgs::Container_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_interfaces_test_msgs::Container_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_interfaces_test_msgs::Container_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f61966137cfe6d8e76e4d1bf7bd78bdb";
  }

  static const char* value(const ::common_interfaces_test_msgs::Container_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf61966137cfe6d8eULL;
  static const uint64_t static_value2 = 0x76e4d1bf7bd78bdbULL;
};

template<class ContainerAllocator>
struct DataType< ::common_interfaces_test_msgs::Container_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_interfaces_test_msgs/Container";
  }

  static const char* value(const ::common_interfaces_test_msgs::Container_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_interfaces_test_msgs::Container_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SubContainer cont1\n\
bool cont1_valid\n\
\n\
SubContainer cont2\n\
\n\
SubContainer cont3\n\
bool cont3_valid\n\
\n\
SubContainer cont4\n\
\n\
uint32 field1\n\
bool field1_valid\n\
\n\
uint32 field2\n\
\n\
\n\
================================================================================\n\
MSG: common_interfaces_test_msgs/SubContainer\n\
SubSubContainer sub1\n\
bool sub1_valid\n\
\n\
SubSubContainer sub2\n\
\n\
float64 field1\n\
bool field1_valid\n\
\n\
float64 field2\n\
\n\
\n\
================================================================================\n\
MSG: common_interfaces_test_msgs/SubSubContainer\n\
uint32 field1\n\
bool field1_valid\n\
\n\
uint32 field2\n\
\n\
";
  }

  static const char* value(const ::common_interfaces_test_msgs::Container_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_interfaces_test_msgs::Container_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cont1);
      stream.next(m.cont1_valid);
      stream.next(m.cont2);
      stream.next(m.cont3);
      stream.next(m.cont3_valid);
      stream.next(m.cont4);
      stream.next(m.field1);
      stream.next(m.field1_valid);
      stream.next(m.field2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Container_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_interfaces_test_msgs::Container_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_interfaces_test_msgs::Container_<ContainerAllocator>& v)
  {
    s << indent << "cont1: ";
    s << std::endl;
    Printer< ::common_interfaces_test_msgs::SubContainer_<ContainerAllocator> >::stream(s, indent + "  ", v.cont1);
    s << indent << "cont1_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cont1_valid);
    s << indent << "cont2: ";
    s << std::endl;
    Printer< ::common_interfaces_test_msgs::SubContainer_<ContainerAllocator> >::stream(s, indent + "  ", v.cont2);
    s << indent << "cont3: ";
    s << std::endl;
    Printer< ::common_interfaces_test_msgs::SubContainer_<ContainerAllocator> >::stream(s, indent + "  ", v.cont3);
    s << indent << "cont3_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cont3_valid);
    s << indent << "cont4: ";
    s << std::endl;
    Printer< ::common_interfaces_test_msgs::SubContainer_<ContainerAllocator> >::stream(s, indent + "  ", v.cont4);
    s << indent << "field1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.field1);
    s << indent << "field1_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.field1_valid);
    s << indent << "field2: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.field2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_INTERFACES_TEST_MSGS_MESSAGE_CONTAINER_H
